services:
  - type: web
    name: e-tour-backend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: SIMPLE_HEARTBEAT_ENABLED
        value: "true"
      - key: HEARTBEAT_INTERVAL
        value: "30000"
      - key: SELF_PING_ENABLED
        value: "true"
      - key: LOG_HEARTBEAT
        value: "false"
    # Add your other environment variables here
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: e-tour-db
    #     property: connectionString
    # - key: JWT_SECRET
    #   generateValue: true
    # - key: CLOUDINARY_CLOUD_NAME
    #   value: your-cloudinary-name
    # - key: CLOUDINARY_API_KEY
    #   value: your-api-key
    # - key: CLOUDINARY_API_SECRET
    #   value: your-api-secret
    # - key: SMTP_HOST
    #   value: smtp.gmail.com
    # - key: SMTP_PORT
    #   value: 587
    # - key: SMTP_USER
    #   value: your-email@gmail.com
    # - key: SMTP_PASS
    #   value: your-app-password

# Optional: Add database if needed
# databases:
#   - name: e-tour-db
#     databaseName: etour
#     user: etour_user
#     region: oregon
#     plan: starter
